config/routes.rb
StartupJob::Application.routes.draw do
  resources :deposits, :except => [:destroy, :edit, :update]
  resources :profiles, :only => [:show, :edit, :update]
  resources :jobs, :except => [:index]
  
  devise_for :users, :controllers => { :sessions => "users/sessions" }

  match "tags/:tag_id" => "tags#show", :as => :show_tag
  match "tags" => "tags#index", :as => :index_tags
  match "categories/:category_id/show" => "categories#show", :as => :show_category
  match "categories" => "categories#index", :as => :index_category
  match "browse_by/:filter/:q" => "jobs#filtering", :as => :browse_by

  root :to => 'jobs#index'
  

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  attr_accessible :bio, :city, :github_url, :job_notif, :name, :portofolio_url, :user_id

  #relations
  belongs_to :user
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_filter :authenticate_user!
  
  # GET /profiles/1
  # GET /profiles/1.json
  def show
    @profile = Profile.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @profile }
    end
  end

  # GET /profiles/1/edit
  def edit
    @profile = Profile.find(params[:id])
  end

  # PUT /profiles/1
  # PUT /profiles/1.json
  def update
    @profile = Profile.find(params[:id])

    respond_to do |format|
      if @profile.update_attributes(params[:profile])
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/edit.html.erb
<h1>Editing profile</h1>

<%= form_for(@profile) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :bio %><br />
    <%= f.text_area :bio %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :portofolio_url %><br />
    <%= f.text_field :portofolio_url %>
  </div>
  <div class="field">
    <%= f.label :github_url %><br />
    <%= f.text_field :github_url %>
  </div>
  <div class="field">
    <%= f.label :job_notif %><br />
    <%= f.number_field :job_notif %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= link_to 'Show', @profile %>

app/views/profiles/show.html.erb
<p>
  <b>Name:</b>
  <%= @profile.name %>
</p>

<p>
  <b>Bio:</b>
  <%= @profile.bio %>
</p>

<p>
  <b>City:</b>
  <%= @profile.city %>
</p>

<p>
  <b>Portofolio url:</b>
  <%= @profile.portofolio_url %>
</p>

<p>
  <b>Github url:</b>
  <%= @profile.github_url %>
</p>

<p>
  <b>Job notif:</b>
  <%= @profile.job_notif %>
</p>

<%= link_to 'Edit', edit_profile_path(@profile) %>