config/routes.rb
StartupJob::Application.routes.draw do
  resources :deposits, :except => [:destroy, :edit, :update]
  resources :profiles, :only => [:show, :edit, :update]
  resources :jobs, :except => [:index]
  
  devise_for :users, :controllers => { :sessions => "users/sessions" }

  match "tags/:tag_id" => "tags#show", :as => :show_tag
  match "tags" => "tags#index", :as => :index_tags
  match "categories/:category_id/show" => "categories#show", :as => :show_category
  match "categories" => "categories#index", :as => :index_category
  match "browse_by/:filter/:q" => "jobs#filtering", :as => :browse_by

  root :to => 'jobs#index'
  

end

app/models/job.rb
class Job < ActiveRecord::Base
  attr_accessible :apply_to, :category_id, :company_name, :description, :email, 
    :location, :publish, :title, :url, :highlight, :skill_list, :job_type, :salary, :user_id

  #validation
  validates :apply_to, :category_id, :company_name, :description, :email,
    :location, :title, :url, :skill_list, :job_type, :salary, :presence => true

  # Alias for acts_as_taggable_on :tags
  acts_as_taggable
  acts_as_taggable_on :skills

  #job relations
  belongs_to :category
  belongs_to :user
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show, :filtering]
  
  # GET /jobs
  # GET /jobs.json
  def index
    option_selections
    @jobs = Job.all.group_by(&:category_id)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @jobs }
    end
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
    @job = Job.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @job }
    end
  end

  # GET /jobs/new
  # GET /jobs/new.json
  def new
    option_selections
    @job = Job.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @job }
    end
  end

  # GET /jobs/1/edit
  def edit
    option_selections
    @job = Job.find(params[:id])
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(params[:job])

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render json: @job, status: :created, location: @job }
      else
        option_selections
        format.html { render action: "new" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /jobs/1
  # PUT /jobs/1.json
  def update
    @job = Job.find(params[:id])

    respond_to do |format|
      if @job.update_attributes(params[:job])
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { head :no_content }
      else
        option_selections
        format.html { render action: "edit" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job = Job.find(params[:id])
    @job.destroy

    respond_to do |format|
      format.html { redirect_to jobs_url }
      format.json { head :no_content }
    end
  end

  def filtering
    @objects = if params[:filter].eql?("salary")
      Job.where(:salary => SALARY[params[:q].to_i-1]).paginate(:page => params[:page], :per_page => PERPAGE)
    else
      Job.where(:job_type => params[:q]).paginate(:page => params[:page], :per_page => PERPAGE)
    end

    respond_to do |format|
      format.html # filtering.html.erb
      format.json { render json: @objects }
    end
  end

  protected

  def option_selections
    @categories = Category.order(:title)
    @types = TYPE
    @salaries = SALARY
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
        <% @job.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <label for="job_title">Job Title</label><br />
    <%= f.text_field :title, :style => "width: 300px;", :placeholder => "“Ruby Programmer” or “iOS Programmer”" %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br />
    <%= f.select(:category_id, @categories.collect {|p| [ p.title, p.id ] }, { :prompt => "-- Select Category --" }, :style => "width: 300px;") %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location, :style => "width: 300px;", :placeholder => " “New York”, “Madrid, Spain”, or “Anywhere” " %>
  </div>
  <div class="field">
    <label for="job_description">Job Description</label><br />
    <%= f.text_area :description, :placeholder => "Enter text ...", :style => "width: 700px;" %>
  </div>
  <div class="field">
    <%= f.label :job_type %><br />
    <%= f.select(:job_type, @types.collect {|t| [ t.capitalize, t ] }, { :prompt => "-- Select Type --" }, :style => "width: 300px;") %>
  </div>
  <div class="field">
    <%= f.label :salary %><br />
    <%= f.select(:salary, @salaries.collect {|s| [ s.capitalize, s ] }, :style => "width: 300px;") %>
  </div>
  <div class="field">
    <label for="job_apply_to">How to apply</label><br />
    <%= f.text_area :apply_to, :style => "width: 300px;", :rows => 5, :placeholder => "Example: Send a resume and cv to elvin@funjobs.com" %>
  </div>

  <h2>Tell us about your company</h2>
  
  <div class="field">
    <%= f.label :company_name %><br />
    <%= f.text_field :company_name, :style => "width: 300px;", :placeholder => "Enter your company or organization’s name." %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url, :style => "width: 300px;", :placeholder => "Example: http://www.twitter.com" %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email, :style => "width: 300px;", :placeholder => "This is where we’ll send your receipt and confirmation email." %>
  </div>
  <div class="field">
    <label for="job_skill_list">Tag skills</label><br />
    <%= f.text_field :skill_list, :style => "width: 300px;", :placeholder => "Example : Ruby, rails, android, twitter.com, iOS" %>
  </div>
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <br />
  <div class="actions">
    <%= f.submit 'Publish Your Job', :class => "btn btn-primary btn-large" %> or <button class="btn btn-large" type="button">Cancel</button>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing job</h1>

<%= render 'form' %>

<%= link_to 'Show', @job %>

<br />

app/views/jobs/filtering.html.erb
<h1>Browse by : <%= params[:filter] %></h1>
<% if params[:filter].eql?("salary") %>
  <h3>Range salary : <%= SALARY[params[:q].to_i-1] %></h3>
<% else %>
  <h3>Type : <%= params[:q] %></h3>
<% end %>
<br />
<br />

<div id="job_list">
  <ul>
    <% @objects.each do |job| %>
      <li>
        <a href="/jobs/<%= job.id %>">
          <span class="job_type"><%= job.job_type %></span> --
          <span class="title"><%= job.title %></span>
          <span class="location"><%= job.location %></span>
          at
          <span class="company"><%= job.company_name %></span>
          <span class="date"></span>
        </a>
      </li>
    <% end %>
  </ul>
</div>

<%= will_paginate @objects %>

app/views/jobs/index.html.erb
<h1>Jobs</h1>

<br />
<br />

<div id="job_list">
  <% @categories.each_with_index do |category, index| %>
    <div id="category-<%= index+1 %>">
      <% if @jobs[category.id] %>
      <h3><%= link_to category.title, show_category_path(:category_id => category.id) %></h3>
      <ul>
        <% @jobs[category.id].each do |job| %>
          <li>
            <a href="/jobs/<%= job.id %>">
              <span class="job_type"><%= job.job_type %></span> -- 
              <span class="title"><%= job.title %></span>
              <span class="location"><%= job.location %></span>
              at
              <span class="company"><%= job.company_name %></span>
              <span class="date"></span>
            </a>
          </li>
        <% end %>
      </ul>
      <% end %>
    </div>
  <% end %>
</div>

<br />

app/views/jobs/new.html.erb
<h1>Job Info</h1>
<br />

<%= render 'form' %>

<br />

app/views/jobs/show.html.erb
<div>
  <h1> <%= @job.title %> </h1>
  <br />
  <h2>
    <span class="company"><%= @job.company_name %>. </span>
    <br />
    <span class="location">Location: <%= @job.location %></span>
    <br />
    <%= @job.url %>
  </h2>
</div>

<br />
<div>
  <%= @job.description.html_safe %>
</div>

<br />
<div>
  <h3>Apply for this position</h3>
  <p>
    <%= @job.apply_to %>
  </p>
</div>

<div>
  <div class="tag_lists">
    Tag Lists : 
    <% @job.skills.each do |skill| %>
      <%= link_to skill.name, show_tag_path(:tag_id => skill.id) %>
    <% end %>
  </div>
  <div class="salary">
    Salary :
    <%= @job.salary %>
  </div>
  <div class="job_type">
    Job Type :
    <%= @job.job_type %>
  </div>
</div>

<br />

<% if user_signed_in? %>
  <% if current_user.id.eql?(@job.user_id) %>
    <%= link_to "Edit", edit_job_path(@job) %>
  <% end %>
<% end %>

<br />