config/routes.rb
StartupJob::Application.routes.draw do
  resources :deposits, :except => [:destroy, :edit, :update]
  resources :profiles, :only => [:show, :edit, :update]
  resources :jobs, :except => [:index]
  
  devise_for :users, :controllers => { :sessions => "users/sessions" }

  match "tags/:tag_id" => "tags#show", :as => :show_tag
  match "tags" => "tags#index", :as => :index_tags
  match "categories/:category_id/show" => "categories#show", :as => :show_category
  match "categories" => "categories#index", :as => :index_category
  match "browse_by/:filter/:q" => "jobs#filtering", :as => :browse_by

  root :to => 'jobs#index'
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "FunJobs" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
<%#= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
<%#= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
<%#= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
<%#= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
<%#= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">FunJobs</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Post new Job", new_job_path  %></li>
              <% if user_signed_in? %>
                <li><%= link_to "Browse Startup", deposits_path %></li>
                <li><%= link_to "Settings", edit_user_registration_path  %></li>
                <li><%= link_to "Account", profile_path(current_user.profile)  %></li>
                <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete  %></li>
              <% else %>
                <li><%= link_to "Deposit Resume", new_deposit_path%></li>
                <li><%= link_to "Register", new_user_registration_path  %></li>
                <li><%= link_to "Login", new_user_session_path  %></li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="span9">
          <br />
          <br />
          <%= bootstrap_flash %>
          <br />
          <%= yield %>
          <br />
          <br />
        </div>
        <div class="span3">
          <br />
          <div class="well sidebar-nav">
            <h3>Browse by :</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Menu</li>
              <li><%= link_to "Tags", index_tags_path  %></li>
              <li><%= link_to "Categories", index_category_path  %></li>
              <li><%= link_to "Job Types", "#"  %>
                <ul>
                  <% TYPE.each do |type| %>
                    <li><%= link_to type, "/browse_by/job_type/#{type}" %></li>
                  <% end %>
                </ul>
              </li>
              <li><%= link_to "Salaries", "#"  %>
                <ul>
                  <% SALARY.each_with_index do |salary, i| %>
                    <li><%= link_to salary, "/browse_by/salary/#{i+1}" %></li>
                  <% end %>
                </ul>
              </li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>FunJobs 2013</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application", "bootstrap-wysihtml5" %>
    <script type="text/javascript">
      $("#job_description, #deposit_resume").wysihtml5(
      {
        "font-styles": false, //Font styling, e.g. h1, h2, etc. Default true
        "emphasis": true, //Italics, bold, etc. Default true
        "lists": true, //(Un)ordered lists, e.g. Bullets, Numbers. Default true
        "html": true, //Button which allows you to edit the generated HTML. Default false
        "link": true, //Button to insert a link. Default true
        "image": true, //Button to insert an image. Default true,
        "color": false //Button to change color of font
      });
    </script>
  </body>
</html>